let { lang } = require('../setting.json');
let langs = {
  eng: {
    arr: [
      ['thisPC', 'This Computer'],
      ['recFiles', 'Recent Files'],
      ['recFolders', 'Recent Folders'],
      ['searchInput', 'Search Folder...'],
      ['fmText', 'File Manager'],
      ['titleUp', 'Visit parent folder'],
      ['titleLast', 'Visit last step'],
      ['titleSearch', 'Search In Current folder'],
      ['titleAlph', 'Sort by Alphabet'],
      ['titleSize', 'Sort by Size'],
      ['titleCopy', 'Copy Path'],
    ],
    singles: {
      sortedBy: 'Sorted by',
      size: 'Size',
      emptyFolder: 'Folder is empty',
      settings: 'Settings',
      language: 'Language:',
      sPath: 'Starting path:',
      nori: 'Number of recent items:',
      safeMode: ' Safe mode:',
      sae: 'Save and Exit',
      enabled: 'Enabled',
      disabled: 'Disabled',
      properties: 'properties',
      fileType: 'File Type:',
      location: 'Location',
      createdAt: 'Created At:',
      lChanges: 'Last Changes:',
      lOpen: 'Last opened',
    },
  },
  de: {
    arr: [
      ['thisPC', 'Dieser Computer'],
      ['recFiles', 'Letzte Dateien'],
      ['recFolders', 'Letzte Ordner'],
      ['searchInput', 'Ordner durchsuchen...'],
      ['fmText', 'Dateimanager'],
      ['titleUp', 'Besuchen Sie den übergeordneten Ordner'],
      ['titleLast', 'Besuchen Sie den letzten Schritt'],
      ['titleSearch', 'Im aktuellen Ordner suchen'],
      ['titleAlph', 'Nach Alphabet sortieren'],
      ['titleSize', 'Nach Größe sortiert'],
      ['titleCopy', 'Pfad kopieren'],
    ],
    singles: {
      sortedBy: 'Sortiert nach',
      size: 'Größe',
      emptyFolder: 'Ordner ist leer',
      settings: 'Einstellungen',
      language: 'Sprache:',
      sPath: 'Startpfad:',
      nori: 'Anzahl der letzten Elemente:',
      safeMode: 'Abgesicherter Modus:',
      sae: 'Speichern und beenden',
      enabled: 'Aktiviert',
      disabled: 'Deaktiviert',
      properties: 'Eigenschaften',
      fileType: 'Dateityp:',
      location: 'Standort',
      createdAt: 'Erstellt am:',
      lChanges: 'Letzte Änderungen:',
      lOpen: 'Zuletzt geöffnet',
    },
  },
  cs: {
    arr: [
      ['thisPC', 'Tento Počítač'],
      ['recFiles', 'Poslední Soubory'],
      ['recFolders', 'Poslední Složky'],
      ['searchInput', 'Hledej...'],
      ['fmText', 'Správce Souborů'],
      ['titleUp', 'Navštiv složku o 1 nad'],
      ['titleLast', 'Navštiv poslední krok'],
      ['titleSearch', 'Hledej v aktuální složce'],
      ['titleAlph', 'Seřaď podle abecedy'],
      ['titleSize', 'Seřaď podle velikosti'],
      ['titleCopy', 'Zkopíruj cestu'],
    ],
    singles: {
      sortedBy: 'Seřazeno podle',
      size: 'Velikosti',
      emptyFolder: 'Složka je prázdná',
      settings: 'Nastavení',
      language: 'Jazyk:',
      sPath: 'Starting path:',
      nori: 'Počet posledních položek:',
      safeMode: 'Bezpečný režim:',
      sae: 'Save and Exit',
      enabled: 'Povoleno',
      disabled: 'Zakázáno',
      properties: 'vlastnosti',
      fileType: 'Typ souboru:',
      location: 'Umístění',
      createdAt: 'Vytvořeno v:',
      lChanges: 'Last Changes:',
      lOpen: 'Naposledy otevřeno',
    },
  },
  esp: {
    arr: [
      ['thisPC', 'Este computador'],
      ['recFiles', 'Archivos recientes'],
      ['recFolders', 'Carpetas recientes'],
      ['searchInput', 'Buscar...'],
      ['fmText', 'Administrador de archivos'],
      ['titleUp', 'Visite la carpeta 1 arriba'],
      ['titleLast', 'Visita el último paso'],
      ['titleSearch', 'Buscar en la carpeta actual'],
      ['titleAlph', 'Ordenar por Alfabeto'],
      ['titleSize', 'Ordenado por tamaño'],
      ['titleCopy', 'Copiar ruta'],
    ],
    singles: {
      sortedBy: 'Ordenado por',
      size: 'Tamaño',
      emptyFolder: "'La carpeta está vacía",
      settings: 'Configuración',
      language: 'idioma',
      sPath: 'Ruta de inicio:',
      nori: 'Número de elementos recientes:',
      safeMode: 'Modo seguro:',
      sae: 'Guardar y salir',
      enabled: 'Habilitado',
      disabled: 'Desactivado',
      properties: 'propiedades',
      fileType: 'Tipo de archivo:',
      location: 'Ubicación',
      createdAt: 'Creado en:',
      lChanges: 'Últimos cambios:',
      lOpen: 'Último abierto',
    },
  },
  sk: {
    arr: [
      ['thisPC', 'Tento počítač'],
      ['recFiles', 'Nedávne súbory'],
      ['recFolders', 'Nedávne zložky'],
      ['searchInput', 'Hľadaj zložku...'],
      ['fmText', 'Správca súborov'],
      ['titleUp', 'Navštívte rodičovskú zložku'],
      ['titleLast', 'Navštívte posledný krok'],
      ['titleSearch', 'Hľadať v aktuálné zložke'],
      ['titleAlph', 'Zoradiť podľa abecedy'],
      ['titleSize', 'Zoradiť podľa veľkosti'],
      ['titleCopy', 'Kopírovať cestu'],
    ],
    singles: {
      sortedBy: 'Zoradené podľa',
      size: 'Veľkosti',
      emptyFolder: 'zložka je prázdná',
      settings: 'Nastavenia',
      language: 'Jazyk:',
      sPath: 'Počiatočná cesta:',
      nori: 'Počet posledných položiek:',
      safeMode: 'Bezpečný režim:',
      sae: 'Uložiť a ukončiť',
      enabled: 'Povolené',
      disabled: 'Zakázané',
      properties: 'vlastnosti',
      fileType: 'Typ súboru:',
      location: 'Poloha',
      createdAt: 'Vytvorené v:',
      lChanges: 'Last Changes:',
      lOpen: 'Naposledy otvorené',
    },
  },
  pl: {
    arr: [
      ['thisPC', 'Ten komputer'],
      ['recFiles', 'Ostatnie pliki'],
      ['recFolders', 'Ostatnie foldery'],
      ['searchInput', 'Przeszukaj folder...'],
      ['fmText', 'Menedżer plików'],
      ['titleUp', 'Odwiedź folder nadrzędny'],
      ['titleLast', 'Odwiedź ostatni krok'],
      ['titleSearch', 'Szukaj w bieżącym folderze'],
      ['titleAlph', 'Sortuj według alfabetu'],
      ['titleSize', 'Sortuj według rozmiaru'],
      ['titleCopy', 'Kopiuj ścieżkę'],
    ],
    singles: {
      sortedBy: 'Posortowane według',
      size: 'Rozmiaru',
      emptyFolder: 'Folder jest pusty',
      settings: 'Ustawienia',
      language: 'Język:',
      sPath: 'Ścieżka początkowa:',
      nori: 'Liczba ostatnich pozycji:',
      safeMode: ' Tryb awaryjny:',
      sae: 'Zapisz i wyjdź',
      enabled: 'Włączone',
      disabled: 'Wyłączone',
      properties: 'właściwości',
      fileType: 'Typ pliku:',
      location: 'Lokalizacja',
      createdAt: 'Utworzono w:',
      lChanges: 'Ostatnie zmiany:',
      lOpen: 'Ostatnio otwarte',
    },
  },
  ch: {
    arr: [
      ['thisPC', '这台电脑'],
      ['recFiles', '最近的文件'],
      ['recFolders', '最近的文件夹'],
      ['searchInput', '搜索文件夹...'],
      ['fmText', '文件管理器'],
      ['titleUp', '访问父文件夹'],
      ['titleLast', '访问最后一步'],
      ['titleSearch', '在当前文件夹中搜索'],
      ['titleAlph', '按字母顺序排序'],
      ['titleSize', '按尺寸排序'],
      ['titleCopy', '复制路径'],
    ],
    singles: {
      sortedBy: '排序',
      size: '尺寸',
      emptyFolder: '文件夹为空',
      settings: '设置',
      language: '语言:',
      sPath: '起始路径：',
      nori: '最近的项目数：',
      safeMode: '安全模式:',
      sae: '保存并退出',
      enabled: '启用',
      disabled: '禁用',
      location: '属性',
      fileType: '文件类型：',
      location: '位置',
      createdAt: '创建时间：',
      lChanges: '上次更改：',
      lOpen: '上次打开',
    },
  },
  rus: {
    arr: [
      ['thisPC', 'Этот компьютер'],
      ['recFiles', 'Недавние файлы'],
      ['recFolders', 'Недавняя папка'],
      ['searchInput', 'Папка поиска...'],
      ['fmText', 'Файловый менеджер'],
      ['titleUp', 'Доступ к родительской папке'],
      ['titleLast', 'Посетите последний шаг'],
      ['titleSearch', 'Искать в текущей папке'],
      ['titleAlph', 'Сортировать по алфавиту'],
      ['titleSize', 'Сортировать по размеру'],
      ['titleCopy', 'Копировать путь'],
    ],
    singles: {
      sortedBy: 'отсортировано по',
      size: 'размер',
      emptyFolder: 'Папка пуста',
      settings: 'Настройки',
      language: 'Язык:',
      sPath: 'Начальный путь:',
      nori: 'Количество недавних записей:',
      safeMode: 'Безопасный режим:',
      sae: 'Сохранить и выйти',
      enabled: 'Включено',
      disabled: 'Disabled',
      properties: 'свойства',
      fileType: 'Тип файла:',
      location: 'Местоположение',
      createdAt: 'Создано в:',
      lChanges: 'Последние изменения:',
      lOpen: 'Последний раз открывался',
    },
  },
};
let curLang = langs[lang];
let langsOpts = `<option value="${lang}">${lang}</option>`;
let langsArr = [lang];
function handleLang() {
  curLang = langs[lang];
  langsOpts = `<option value="${lang}">${lang}</option>`;
  langsArr = [lang];
  for (let i = 0; i < curLang.arr.length; ++i) {
    let el = document.getElementById(curLang.arr[i][0]);
    if (el.nodeName.toLowerCase() == 'input') {
      el.placeholder = curLang.arr[i][1];
    } else if (curLang.arr[i][0].startsWith('title')) {
      el.title = curLang.arr[i][1];
    } else {
      el.innerText = curLang.arr[i][1];
    }
  }
  for (l in langs) {
    if (l != lang) {
      langsOpts += `<option value="${l}">${l}</option>`;
      langsArr.push(l);
    }
  }
}
for (l in langs) {
  if (l != lang) {
    langsOpts += `<option value="${l}">${l}</option>`;
    langsArr.push(l);
  }
}
let singleds = {
  settings: 'Settings',
  language: 'Language:',
  sPath: 'Starting path:',
  nori: 'Number of recent items:',
  safeMode: ' Safe mode:',
  sae: 'Save and Exit',
};
